const STORAGE_KEY = '2failure-last-fun-fact-index';

export const FUN_FACTS = [
  'Honey never spoils. Archaeologists have eaten 3,000-year-old honey.',
  'Octopuses have three hearts and blue blood.',
  'A day on Venus is longer than a year on Venus.',
  'Bananas are berries, but strawberries are not.',
  'Wombat poop is cube-shaped.',
  'Sharks existed before trees.',
  'Scotland\'s national animal is the unicorn.',
  'A single cloud can weigh over a million pounds.',
  'Sloths can hold their breath longer than dolphins.',
  'The heart of a blue whale is roughly the size of a small car.',
  'Humans share about 60% of their DNA with bananas.',
  'Oxford University is older than the Aztec Empire.',
  'Sea otters hold hands while sleeping so they don\'t drift apart.',
  'A bolt of lightning is five times hotter than the surface of the sun.',
  'Koalas have fingerprints nearly identical to humans.',
  'Cows have best friends and get stressed when separated.',
  'Butterflies taste with their feet.',
  'Apples float because they are about 25% air.',
  'The smell of rain has a name: petrichor.',
  'Dolphins sleep with one eye open.',
  'A snail can sleep for three years.',
  'Giraffes have the same number of neck vertebrae as humans: seven.',
  'Elephants can\'t jump.',
  'Cats can\'t taste sweetness.',
  'The moon is drifting away from Earth by about 1.5 inches per year.',
  'Saturn could float in water if you had a bathtub big enough.',
  'One million Earths could fit inside the sun.',
  'A teaspoon of neutron star would weigh about a billion tons.',
  'The International Space Station travels at about 17,500 mph.',
  'Football players run about 7 miles per game on average.',
  'A marathon is 26.2 miles because of a Greek legend.',
  'A regulation basketball hoop is exactly 10 feet high.',
  'Swimming burns more calories than running at equal effort.',
  'Carrots were originally purple.',
  'Peanuts are legumes, not nuts.',
  'The most stolen food in the world is cheese.',
  'Ketchup was once sold as medicine.',
  'Avocados are botanically berries.',
  'The fortune cookie was invented in California, not China.',
  'Potatoes were the first food grown in space.',
  'The popsicle was invented by an 11-year-old by accident.',
  'Maine is the only U.S. state with a one-syllable name.',
  'Russia spans 11 time zones.',
  'Canada has more lakes than the rest of the world combined.',
  'Iceland has no mosquitoes.',
  'Australia is wider than the moon.',
  'Vatican City is the smallest country in the world.',
  'Mount Everest grows about 4 millimeters per year.',
  'The Dead Sea is so salty you can float easily.',
  'The piano has 88 keys.',
  'Mozart wrote his first symphony at age eight.',
  'Whales can sing songs that travel hundreds of miles underwater.',
  'Dogs can learn over 150 words.',
  'Crows can solve multi-step puzzles.',
  'Bees can recognize human faces.',
  'Pigs are considered as smart as young children.',
  'The mantis shrimp punches with the force of a bullet.',
  'The Greenland shark can live over 400 years.',
  'The human body has 206 bones.',
  'Fingernails grow faster than toenails.',
  'Sneezes can travel over 100 mph.',
  'Humans are the only animals that blush.',
  'Your left lung is slightly smaller to make room for your heart.',
  'The liver can regenerate much of itself after damage.',
  'The femur is stronger than concrete pound for pound.',
  'Laughing boosts the immune system.',
  'The human brain is about 75% water.',
  'Music can improve workout performance.',
  'The first computer bug was a real moth.',
  'The first domain name ever registered was Symbolics.com.',
  'The first webcam watched a coffee pot at Cambridge University.',
  'The first emoji set was created in Japan in 1999.',
  'The first tweet ever posted was "just setting up my twttr."',
  'The first photo uploaded to Instagram was of a dog and a foot.',
  'The first item sold on eBay was a broken laser pointer.',
  'The first Amazon book sold was about artificial intelligence.',
  'The microwave oven was invented after a melted candy bar in a lab.',
  'Bubble wrap was originally designed as wallpaper.',
  'The LEGO brick design from 1958 still fits modern LEGO bricks.',
  'Play-Doh was first sold as wallpaper cleaner.',
  'Coca-Cola was originally green.',
  'The shortest commercial flight in the world lasts under two minutes.',
  'There is a basketball court on the top floor of the U.S. Supreme Court building.',
  'The longest hiccuping spree on record lasted 68 years.',
  'A jiffy is an actual unit of time: about 1/100 of a second.',
  'The dot over a lowercase "i" or "j" is called a tittle.',
  'The word "set" has more definitions than any other word in English.',
  'The Great Wall of China is not visible from space with the naked eye.',
  'Cleopatra lived closer in time to the Moon landing than to the Great Pyramid.',
  'Nintendo was founded in 1889 as a playing card company.',
  'The inventor of the Pringles can is buried in one.',
  'Hot water can freeze faster than cold water under certain conditions.',
  'Oxford University has a library older than the Aztec Empire.',
  'A group of flamingos is called a flamboyance.',
  'A group of owls is called a parliament.',
  'A group of ravens is called an unkindness.',
  'A group of kangaroos is called a mob.',
  'A group of zebras is called a dazzle.',
  'A group of pandas is called an embarrassment.',
  'The Eiffel Tower can grow over six inches taller in summer heat.',
  'The Sahara Desert was green and lush about 6,000 years ago.',
  'Japan has over 200 volcanoes.',
  'The Nile and the Amazon are close contenders for the longest river.',
  'New York City was briefly named New Amsterdam.',
  'The Beatles hold the record for most Billboard Hot 100 hits.',
  'The longest song ever recorded is over 13 hours long.',
  'Axolotls can regrow limbs and parts of their brain.',
  'Tardigrades can survive in the vacuum of space.',
  'The pistol shrimp creates a bubble hotter than the sun for a split second.',
  'The Arctic tern migrates from pole to pole every year.',
  'The cheetah is the fastest land animal.',
  'Horses can\'t breathe through their mouths.',
  'Rabbits can\'t vomit.',
  'A crocodile cannot stick its tongue out.',
  'Goldfish can remember things for months, not just seconds.',
  'Chickens can dream.',
  'Parrots can live over 80 years.',
  'The human nose can detect about a trillion different scents.',
  'Your skeleton completely renews itself about every 10 years.',
  'An adult human body has about 37 trillion cells.',
  'The human eye can distinguish about 10 million colors.',
  'The cornea is one of the few body parts with no blood supply.',
  'Babies are born with about 300 bones; many fuse as they grow.',
  'The small intestine is about 20 feet long.',
  'The strongest muscle by weight is the masseter in your jaw.',
  'The average person walks the equivalent of three times around the world in a lifetime.',
  'Reading reduces stress faster than listening to music for many people.',
  'Chewing gum while cutting onions may reduce tears.',
  'Cold showers can increase alertness for some people.',
  'The placebo effect works even when people know they are taking a placebo.',
  'Yawns are contagious because of mirror neurons.',
  'The 100-meter dash world record is under 9.6 seconds.',
  'The first sub-4-minute mile was run in 1954 by Roger Bannister.',
  'A baseball has 108 stitches.',
  'Golf balls have dimples to fly farther.',
  'Cricket matches can last up to five days.',
  'The Olympic rings represent five inhabited continents.',
  'Surfing returned as an Olympic sport in 2020.',
  'Chocolate was used as currency by the Aztecs.',
  'Saffron is one of the most expensive spices by weight.',
  'The sandwich is named after the Earl of Sandwich.',
  'Wasabi is often horseradish dyed green outside Japan.',
  'Spam stands for spiced ham.',
  'Twinkies originally had a banana cream filling.',
  'The Caesar salad was invented in Mexico.',
  'Cinnamon comes from tree bark.',
  'White chocolate is not technically chocolate.',
  'The croissant is Austrian in origin, not French.',
  'Bubble tea originated in Taiwan in the 1980s.',
  'The first lab-grown burger was eaten in 2013.',
  'The first electric car was built in the 1830s.',
  'The first GPS satellite was launched in 1978.',
  'The first text message was sent in 1992.',
  'The first mobile phone call was made in 1973.',
  'The first email ever sent was "QWERTYUIOP."',
  'The first video game was created in 1958.',
  'The first website is still online at info.cern.ch.',
  'The first photograph of a person was taken in 1838.',
  'The first selfie was taken in 1839 by Robert Cornelius.',
  'The first motion picture was about 2 seconds long.',
  'The first Academy Awards were held in 1929.',
  'The first Nobel Prizes were awarded in 1901.',
  'The first Olympic Games of the modern era were in 1896.',
  'The first FIFA World Cup was held in Uruguay in 1930.',
  'The first Indy 500 was run in 1911.',
  'The first Tour de France was in 1903.',
  'The first Stanley Cup was awarded in 1893.',
  'The first Super Bowl was played in 1967.',
  'The first basketball game was played with peach baskets.',
  'The first volleyball game was called mintonette.',
  'The first badminton rules were written in India in the 1870s.',
  'The first table tennis balls were made of celluloid.',
  'The first skateboard was called a sidewalk surfer in the 1950s.',
  'The first snowboard was called a Snurfer in the 1960s.',
  'The first parkour name came from David Belle in the 1990s.',
  'The first yoga mat was popularized in the 1980s.',
  'The first Pilates method was developed in the 1920s.',
  'The first spin class was invented in the 1980s.',
  'The first Zumba class was created by accident in the 1990s.',
  'The first Tabata protocol was studied in 1996.',
  'The first 10,000 steps-a-day goal came from a Japanese pedometer campaign.',
  'The first carbon-plate running shoe was the Nike Vaporfly in 2017.',
  'The first GPS running watch was the Garmin Forerunner in 2003.',
  'The first rep counting with phone cameras uses pose estimation.',
  'The first AI pose tracking in fitness apps grew in the 2020s.',
  'The first ChatGPT reached 100 million users faster than any app before it.',
  'The first computer to beat a chess grandmaster was Deep Blue in 1997.',
  'The first computer to beat a Go world champion was AlphaGo in 2016.',
  'The first photo of a black hole was published in 2019.',
  'The first gravitational waves were detected in 2015.',
  'The first exoplanet was confirmed in 1992.',
  'The first rover on Mars was Sojourner in 1997.',
  'The first helicopter on Mars was Ingenuity in 2021.',
  'The first human in space was Yuri Gagarin in 1961.',
  'The first woman in space was Valentina Tereshkova in 1963.',
  'The first moon landing was Apollo 11 in 1969.',
  'The first space station was Salyut 1 in 1971.',
  'The first reusable rocket landing was SpaceX in 2015.',
  'The first car in space was a Tesla Roadster launched in 2018.',
  'The first pizza delivered to space was to the ISS in 2001.',
  'The first espresso drunk in space was in 2015 on the ISS.',
  'The first marathon run on a treadmill in space was in 2007.',
  'The first all-female spacewalk was in 2019.',
  'The first fusion ignition milestone was at NIF in 2022.',
  'The first lithium-ion battery was commercialized in 1991.',
  'The first solar cell was built in 1954.',
  'The first wind turbine for electricity was in Scotland in 1887.',
  'The first ATM was installed in London in 1967.',
  'The first barcode scan was on a pack of gum in 1974.',
  'The first QR code was invented in 1994.',
  'The first Bitcoin block was mined in 2009.',
  'The first 3D-printed house was built in 2018.',
  'The first CRISPR gene edit in humans was in 2016.',
  'The first mRNA vaccine approved was for COVID-19 in 2020.',
  'The first polio vaccine was licensed in 1955.',
  'The first X-ray was taken in 1895.',
  'The first MRI scan was performed in 1977.',
  'The first pacemaker was implanted in 1958.',
  'The first test-tube baby was born in 1978.',
  'The first cloning of a mammal was Dolly the sheep in 1996.',
  'The first heart transplant was in 1967.',
  'The first face transplant was in 2005.',
  'The first penicillin discovery was in 1928.',
  'The first periodic table was published by Mendeleev in 1869.',
  'The first laser was built in 1960.',
  'The first LED was invented in 1962.',
  'The first transistor was invented in 1947.',
  'The first programmable computer was the Z3 in 1941.',
  'The first iPhone was released in 2007.',
  'The first Android phone was the HTC Dream in 2008.',
  'The first Kindle was released in 2007.',
  'The first Netflix DVD shipped was Beetlejuice.',
  'The first Spotify stream was of a song by the Hives.',
  'The first YouTube video was filmed at the San Diego Zoo.',
  'The first TikTok launched as Douyin in China in 2016.',
  'The first Fortnite mode was Save the World in 2017.',
  'The first Minecraft alpha was released in 2009.',
  'The first Pokémon games were released in 1996.',
  'The first Mario game was Donkey Kong in 1981.',
  'The first esports tournament was for Spacewar in 1972.',
  'The first speedrun marathon was Awesome Games Done Quick in 2010.',
  'The first VR fitness hit was Beat Saber in 2019.',
  'The first AR game hit was Pokémon GO in 2016.',
  'The first Roomba was sold in 2002.',
  'The first robot dog sold to consumers was Aibo in 1999.',
  'The first drone delivery FAA approvals expanded in the 2020s.',
  'The first self-driving car fatality made headlines in 2018.',
  'The first hyperloop test track was built in Nevada in 2016.',
  'The first bullet train was the Shinkansen in Japan in 1964.',
  'The first Channel Tunnel opened in 1994.',
  'The first Brooklyn Bridge opened in 1883.',
  'The first Golden Gate Bridge opened in 1937.',
  'The first Burj Khalifa opened in 2010.',
  'The first Empire State Building opened in 1931.',
  'The first Eiffel Tower opened in 1889.',
  'The first Statue of Liberty was dedicated in 1886.',
  'The first Roman Colosseum opened in 80 CE.',
  'The first printing press in Europe was by Gutenberg around 1440.',
  'The first compass used for navigation was in China around the 11th century.',
  'The first telescope used for astronomy was by Galileo in 1609.',
  'The first postage stamp was the Penny Black in 1840.',
  'The first crossword puzzle was published in 1913.',
  'The first Monopoly game was based on Atlantic City streets.',
  'The first Rubik\'s Cube was sold in 1980.',
  'The first Ig Nobel Prizes parody real Nobel prizes since 1991.',
  'The first Guinness World Records book was published in 1955.'
];

export function pickFunFact(): string {
  if (FUN_FACTS.length === 0) {
    return 'Fun facts are loading…';
  }

  if (typeof window === 'undefined') {
    return FUN_FACTS[0];
  }

  const lastRaw = localStorage.getItem(STORAGE_KEY);
  const lastIndex =
    lastRaw !== null && Number.isFinite(Number(lastRaw))
      ? Number(lastRaw)
      : -1;

  let nextIndex = Math.floor(Math.random() * FUN_FACTS.length);

  if (FUN_FACTS.length > 1) {
    while (nextIndex === lastIndex) {
      nextIndex = Math.floor(Math.random() * FUN_FACTS.length);
    }
  }

  localStorage.setItem(STORAGE_KEY, String(nextIndex));
  return FUN_FACTS[nextIndex];
}
